### ISSUE TITLE
Parse ruby files for e.g RSpec

### ISSUE THREAD

**Issue by teoljungberg** [tmm1/ripper-tags#100]
If I have an RSpec test and define a method within it - the method is not picked up by the ripper-tags's parser.

```
% cat foo_spec.rb
RSpec.describe 'foo' do
  it do
    expect(helper).to eq('foo')
  end

  def helper
    'foo'
  end
end
% ripper-tags -f- foo_spec.rb
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
```

Is that due to a limitation in the parser that blocks cannot have methods defined within them?

Is this something we could support?

Defining these methods have been a common strategy in my experience.

Example code bases:

FactoryBot:
https://github.com/thoughtbot/factory_bot/blob/6fddc456738185d1f7728b5e1a53afa1ce16a2f6/spec/factory_bot/evaluator_class_definer_spec.rb#L57-L73

**Comment by teoljungberg** [comment]
`ctags` will on the other hand find the method:

```
% cat foo_spec.rb
RSpec.describe 'foo' do
  it do
    expect(helper).to eq('foo')
  end

  def helper
    'foo'
  end
end
% ctags -f- foo_spec.rb
helper  foo_spec.rb     /^  def helper$/;"      f
```

**Comment by mislav** [comment]
Agreed that, ideally, this should be handled.

This sounds similar to #31

**Comment by teoljungberg** [comment]
I didn't find #31 when searching for similar issue before opening this one. Sorry about that.

I'll close this since it's effectively a dupe and subscribe to #31.
