### ISSUE TITLE
Facilitate integration with ctags by introducing --list-kinds

### ISSUE THREAD

**Issue by UmkaDK** [tmm1/ripper-tags#28]
Hi everyone,

First of all, this is more of an enhancement request then an actual bug.

I'm trying to integrate ripper-tags as an external parser into @fishman's [ctags](https://github.com/fishman/ctags), which is currently the most active and consistently updated fork of ctags available. One of the new features the fork brings is the introduction of `--<LANG>-xcmd` option which allows users to define external parser command for specific languages.

However, in order for the external parser to work, it needs to tell ctags a list of all tag kinds for that language. So, I've skimmed through ripper's code base, pulled out all required info and hard coded it into a simple shell wrapper: 

```
c  classes
f  methods
m  modules
F  singleton methods
```

(Please correct me if any of this is wrong)

But, this approach is not ideal and prone to braking whenever ripper-tags adds support for new kinds. It would be much better/cleaner if ripper-tags supported `--list-kinds` and/or `--list-kinds=Ruby` option natively. Any chance this could be added?

PS:  `--<LANG>-xcmd` documentation can be found at https://github.com/fishman/ctags/blob/master/docs/xcmd.rst

**Comment by tmm1** [comment]
Seems reasonable, I would merge a PR that adds this new option.

**Comment by UmkaDK** [comment]
Awesome, thanks @tmm1! I'm a bit swamped with work this month so will have to hold of on making any changes until I free up a bit. But I'll try to send you a PR over the Easter holidays if nobody picks this up before then.
