### ISSUE TITLE
--tag-relative should support yes/no arguments

### ISSUE THREAD

**Issue by toupeira** [tmm1/ripper-tags#35]
[gem-ctags](https://github.com/tpope/gem-ctags) recently started passing `--tag-relative=yes` to ctags, which causes an exception `needless argument: --tag-relative=yes (OptionParser::NeedlessArgument)` in ripper-tags (I'm using a ctags wrapper script that calls ripper-tags for Ruby files).

Can you add optional `yes` and `no` arguments?

**Comment by mislav** [comment]
We can try. Thanks for reporting!
