### ISSUE TITLE
Support --append option

### ISSUE THREAD

**Issue by lowski** [tmm1/ripper-tags#49]
Hi,
I was wondering if it would be possible to support `--append` option.

I'm using [universal ctags](https://github.com/universal-ctags/ctags) for creating `tags` file for other languages than Ruby (JavaScript, CoffeeScript, etc.). Even though universal ctags has better support than exuberant ctags for Ruby (i.e. it support namespaced classes), it still can not handle `--extra=q` option correctly.I would like to use ripper-tags just for ruby files and append ruby tags to ctags file created by universal tags.

**Comment by mislav** [comment]
You could simulate `--append` with:

```sh
{ cat tags
  ripper-tags -R -f - | grep -v '^!_'
} | sort > tags~
mv tags~ tags
```

**Comment by lowski** [comment]
@mislav thanks! I will just drop it to simple script and make alias for that.

**Comment by ejoubaud** [comment]
:+1:

`--append` seems to be part of the expected interface for compatibility with other ctags generators (expected in [this vim plugin](ludovicchabant/vim-gutentags/issues/56) for instance), and a requirement for incremental tags updates.

**Comment by tyok** [comment]
I tried to make mislav's snippet to work and ended up with this, which seems to do the job:

```bash
#!/bin/sh
if [[ $* = *"--append"* ]]; then
  cat ./tags \
    | (cat && ripper-tags -f - ${*/--append}) \
    | grep -v '^!_' \
    | sort \
    > tags~ && mv tags~ tags
else
  ripper-tags $*
fi
```

**Comment by neilgarcia** [comment]
@tyok where did you put that script?

**Comment by tyok** [comment]
@neilgarcia if you put it on `/usr/local/bin/rtags`, you can call it from anywhere, like `rtags -f .`

**Comment by thenoseman** [comment]
Hi! 
This is what I'm using as a ripper-tags wrapper for `vim-gutentags`.

It is a modified version of what @tyok posted which takes the temporary filename vim-gutentags uses into account. 

Seems to work for me but YMMV :)

```bash
#!/bin/sh
#
# Wrapper script to make the "ripper-tags" gem (https://github.com/tmm1/ripper-tags)
# work with vim-gutentags (https://github.com/ludovicchabant/vim-gutentags)
# 
# Put this script in your $PATH, make it executable and configure vim-gutentags like this:
#
# "let g:gutentags_ctags_executable_ruby = 'rtags'"
#
# Parts taken from https://stackoverflow.com/a/14203146/171364 and https://github.com/tmm1/ripper-tags/issues/49
# 
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -f)
    TAGS_FILE_NAME="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ $* = *"--append"* ]]; then
  cat ${TAGS_FILE_NAME} \
    | (cat && ripper-tags --ignore-unsupported-options -f - ${*/--append}) \
    | grep -v '^!_' \
    | sort \
    > tags~ && mv tags~ ${TAGS_FILE_NAME}
else
  ripper-tags --ignore-unsupported-options $*
fi
```

**Comment by ilvez** [comment]
@thenoseman 's script should be explicitly Bash (`#!/bin/bash`), since for example Debian default `sh` is Dash, which fails array syntax (`POSITIONAL=()`). ZSH manages this script as well.
