### ISSUE TITLE
Doesn't work with RSpec source.

### ISSUE THREAD

**Issue by jaytarka** [tmm1/ripper-tags#50]
Very sorry to report this, but it just doesn't seem to be working properly:

This is the incorrect reference, as directed by ripper-tags:
![image](https://cloud.githubusercontent.com/assets/13591429/9735583/bfbe7eb0-5633-11e5-8503-1a04c50ff440.png)

That reference is actually to a private method, so it is certainly incorrect.

This is the correct reference, as directed by rubymine:
![image](https://cloud.githubusercontent.com/assets/13591429/9735586/c7a1fabc-5633-11e5-806c-91900f48dbc7.png)

**Comment by mislav** [comment]
I'm sorry, what are you reporting? I can't understand anything from the screenshots.

Is there a method you expected a tag to be generated for? What was that method? What was the tag that was generated? (Please include relevant output from the tags file.) What was wrong with the tag? What did you expect instead?

**Comment by mislav** [comment]
Can you answer my above questions so I can track down the bug please?

**Comment by mislav** [comment]
Closing due to lack of info.
