### ISSUE TITLE
Support --options=file option

### ISSUE THREAD

**Issue by ejoubaud** [tmm1/ripper-tags#54]
Would be handy for compatibility with exuberant ctags and [vim-guttentags](https://github.com/ludovicchabant/vim-gutentags/issues/56) :)

**Comment by mislav** [comment]
Thanks for the recommendation!

What about options that might be recognized by ctags but not ripper-tags? Should we fail on them?

**Comment by ejoubaud** [comment]
That's a good question. I guess options in the file should work the same as the ones in the cli, i.e. fail when they do.

Regarding the wider topic of options compatibility, the ideal scenario would be supporting all ctags options. `ripper-tags` would be a drop-in replacement to the `exuberant ctags` de-facto standard, as `ag` and `pt` are to `ack`, so there would be perfect integration with the rest of the tags ecosystem. Then I guess that's a lot to ask ;)

Maybe a more realistic option would be to provide an `--ignore-unsupported-options` flag to prevent failure when unknown options are passed.

All the plugins I know of (`vim-tags`, `easytags`, `guttentags`...) let you configure the executable for your ctags generator. If I could set it to `ripper-tags --ignore-unsupported-options`, I wouldn't mind as much that `vim-guttentags` is forcing the `--options` and `--append` ctags options in the call. That way `guttentags` can still be used and compile the tags, even though it doesn't have all the features of the options.

My specific use-case is less about supporting `--options` than being able to use `ripper-tags` with `guttentags`, and a flag to not fail on unsupported options would let me achieve that. Then it would be even better if `--append` was supported too :angel:

**Comment by ejoubaud** [comment]
Not failing on unsupported options by default would also solve my problem, but I wouldn't suggest. The silent fails would likely cause more frustration to more people than this issue.

**Comment by mislav** [comment]
> All the plugins I know of (`vim-tags`, `easytags`, `guttentags`...) let you configure the executable for your ctags generator. If I could set it to `ripper-tags --ignore-unsupported-options`

That's not a bad idea.

**Comment by mislav** [comment]
ripper-tags v0.4.0 doesn't support `--options=FILE` just yet, but it does support `--ignore-unsupported-options` that helps using ripper-tags as a tool swappable with `ctags` and similar tools.

**Comment by k3rni** [comment]
Now after  94c14fb has landed, I think this issue has been fully resolved.
