### ISSUE TITLE
Integration with IDEs

### ISSUE THREAD

**Issue by otoniel-isidoro** [tmm1/ripper-tags#60]
Hi,

I've created the extension [vscode-ruby-ctags](https://marketplace.visualstudio.com/items?itemName=otoniel-isidoro.vscode-ruby-ctags) to integrates vscode with the ripper-tags generator to generate the ctags for ruby projects and to navigate on the code too...  

I'm working on a atom version of this extension and maybe for the sublime-text too...any help I'll be grateful!

Thanks!

**Comment by oca159** [comment]
@otoniel-isidoro it would be awesome!!!, I am looking for a plugin in sublime or atom to autocomplete code in ruby.

Just a question. will it work in windows?
I need to use windows in my work, for personal projects I work in my mac or in a linux machine.

Thanks.

**Comment by mislav** [comment]
@otoniel-isidoro I'm not sure what kind of help do you need exactly, but please let us know if there's anything in our `ripper-tags` CLI that is preventing you from achieving integration.

I'm going to close this one out because it's not actionable for us maintainers.
