### ISSUE TITLE
Jump to SomeClass.some_method

### ISSUE THREAD

**Issue by SnowDiamond** [tmm1/ripper-tags#62]
I'm trying to configure Vim that uses tags generated by ripper-tags.
My vim configuration is:
``` vim
set tags=./tags;
if executable('ripper-tags')
let g:easytags_languages = {'ruby': {'cmd': 'ripper-tags -R --extra=q --exclude=vendor --exclude=.git --exclude=log'}}
endif
let g:easytags_async=1
let g:easytags_auto_highlight=0
let g:easytags_events = ['BufWritePost']
```

On project directory I run command `ripper-tags -R --extra=q --exclude=vendor --exclude=.git --exclude=log` to generate tags.

Than for example I have following code:
``` ruby
class A
   def hello
      1
   end
end

class B
   def hello
      2
   end
end

B.new.hello
```
If set cursor on last line at word `hello` and push `Ctrl + ]` than cursor jumps to definition of hello in class A, instead of class B. Is it known issue or I'm doing something wrong?

**Comment by mislav** [comment]
Hi, sorry for the late reply. You seem to have set up everything correctly and doing everything well. However, you've hit upon a limitation of tags in vim. When you position your cursor on `hello` on the last line and jump to tag, vim will jump to the first `hello` tag it finds, and that one will be `A.hello`, not `B.hello`.

I'm not sure if there is a way to teach vim that `hello` belonged to class `B` when you positioned your cursor.  However, if you do <kbd>g Ctrl+]</kbd>, then vim will let you choose from a list of matching tags.

Does this help?

**Comment by SnowDiamond** [comment]
Yeah, definitely, it will work in this way, thanx!
