### ISSUE TITLE
Cannot jump to functions with a question mark in them (with Emacs)

### ISSUE THREAD

**Issue by debajit** [tmm1/ripper-tags#73]
If I have a Ruby function with a question mark in the name, then I cannot jump to that function name using a TAGS file generated with ripper-tags.

**Comment by mislav** [comment]
This is a problem with Emacs, not ripper-tags.

Ripper-tags generates each tag with the exact method name. In Ruby, method names can end with `?`, `!`, or `=`. Exuberant ctags and universal-ctags also do the same when generating the TAGS file; i.e. if there is a method `def foo?`, a tag called `foo?` will be generated.

The problem in Emacs, I'm guessing, is that jumping to the tag under the cursor doesn't take `?` into account. There is a several year-old fork of etags-select where someone has edited the regex so it's permissive to Ruby method names: https://github.com/emacsmirror/etags-select/compare/master...hbin:master

Ultimately, I believe, this needs to be fixed from within Emacs.
