### ISSUE TITLE
/usr/lib/ruby/gems/2.4.0/gems/ripper-tags-0.4.2/lib/ripper-tags/parser.rb:343:in `process': undefined method `on_assoc'

### ISSUE THREAD

**Issue by dan-higgins** [tmm1/ripper-tags#74]
It looks like an Array of `{ key: value }` Hashes blows up the parser if the `key: value` parts don't have `{ }` around them. It's valid Ruby either way, but the parser requires the braces.

To reproduce:
1. Create a file with these lines:
    ```
    module MyModule
      TEST_DATA = [
        { foo_id1: '1111' }, # Works
        foo_id2: '2222', # Fails
      ]
    end
    ```
2. Run `ripper-tags PATH_TO_FILE_ABOVE`
3. See parser error.

**Comment by mislav** [comment]
Thanks for reporting! New version released.

**Comment by dan-higgins** [comment]
Works! Thanks much for being so fast!
