### ISSUE TITLE
Support `--fields=+l` option 

### ISSUE THREAD

**Issue by jackkinsella** [tmm1/ripper-tags#81]
**Motivation:**
Code completion engines for Vim can be configured to draw upon tag files to power their suggestions. However, some of the major engines (e.g.  [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) ) need the language field to be present in the tag files so that they can give appropriate completions for the type of file you are editing. 

More generally speaking, I think that the more `ripper-tags` resembles `ctags` from an external interface POV, the better. The library should be plug-and-play replacement for the Ruby programmer.

**What needs to be done:**
In implementation terms, this simply means adding a column that reads `language:Ruby` to every line produced by `ripper-tags`. 

Happy to send a PR if you're interested in supporting this option (though LMK if there are any gotchas I should watch out for!)

**Comment by mislav** [comment]
PR welcome! 💟
