### ISSUE TITLE
Custom method modifiers not supported

### ISSUE THREAD

**Issue by tycooon** [tmm1/ripper-tags#94]
I am using a memoization library so some methods are defined like this:

```ruby
memoize def foo
  # ...
end
```

The problem is they are ignored. Can this be fixed somehow?

**Comment by mislav** [comment]
Thanks for reporting!

Ruby has no concept of "custom method modifiers" (the only ones supported are access modifiers), so I'm guessing that `memoize` is simply a class method that receives the result of `def foo`, which is the symbol `:foo`.

I don't know how we could support this in ripper-tags, but it shouldn't be hard. I don't have time to try fixing this right now, so PRs welcome 🙇

**Comment by tycooon** [comment]
Yep, that's how it works. Maybe we can add some CLI argument for adding such methods? Because `private def` works for example (and `private` is a method, at least it can be called with `send`).

**Comment by mislav** [comment]
I don't think a CLI argument would be a way to go; I would ideally imagine that this is just handled out-of-the-box. Maybe we should recognize all `def` expressions regardless of whether they are at "top-level" of a module/class or wrapped inside a modifier or class method call.

**Comment by tycooon** [comment]
I also just remembered that method definitions in RSpec are not working as well since they are not defined in class/module. So what you are saying makes a lot of sense now :)
